name: phi4_env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python Base - HPC Stanage compatible
  - python=3.10

  # Build Tools - Required for Flash Attention compilation on HPC
  - ninja # Fast build system for Flash Attention
  - cmake # Build configuration tool

  # Package Management
  - pip
